In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os
from collections import Counter

In [2]:
news=pd.read_csv('Articles.csv',encoding="ISO-8859-1")

In [3]:
news.head()

Article      Date  \
0  KARACHI: The Sindh government has decided to b...  1/1/2015   
1  HONG KONG: Asian markets started 2015 on an up...  1/2/2015   
2  HONG KONG:  Hong Kong shares opened 0.66 perce...  1/5/2015   
3  HONG KONG: Asian markets tumbled Tuesday follo...  1/6/2015   
4  NEW YORK: US oil prices Monday slipped below $...  1/6/2015   

                                             Heading  NewsType  
0  sindh govt decides to cut public transport far...  business  
1                    asia stocks up in new year trad  business  
2           hong kong stocks open 0.66 percent lower  business  
3             asian stocks sink euro near nine year   business  
4                 us oil prices slip below 50 a barr  business

In [4]:
news['NewsType'].value_counts()

sports      1408
business    1284
Name: NewsType, dtype: int64

In [5]:
news['NewsType'].replace({'sports':0,'business': 1},inplace=True)

In [6]:
news.head()

Article      Date  \
0  KARACHI: The Sindh government has decided to b...  1/1/2015   
1  HONG KONG: Asian markets started 2015 on an up...  1/2/2015   
2  HONG KONG:  Hong Kong shares opened 0.66 perce...  1/5/2015   
3  HONG KONG: Asian markets tumbled Tuesday follo...  1/6/2015   
4  NEW YORK: US oil prices Monday slipped below $...  1/6/2015   

                                             Heading  NewsType  
0  sindh govt decides to cut public transport far...         1  
1                    asia stocks up in new year trad         1  
2           hong kong stocks open 0.66 percent lower         1  
3             asian stocks sink euro near nine year          1  
4                 us oil prices slip below 50 a barr         1

In [7]:
news.shape

(2692, 4)

In [8]:
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2692 entries, 0 to 2691
Data columns (total 4 columns):
Article     2692 non-null object
Date        2692 non-null object
Heading     2692 non-null object
NewsType    2692 non-null int64
dtypes: int64(1), object(3)
memory usage: 84.2+ KB


In [9]:
paper=""
words=[]
for i in range(2692):
    for j in news['Article'][i]:
        paper+=j
words+=paper.split(" ")

In [10]:
len(words)

785472

In [11]:
pen=""
words_heading=[]
for i in range(2692):
    for j in news['Heading'][i]:
        pen+=j
words_heading=pen.split(" ")

In [12]:
len(words_heading)

19435

In [13]:
for i in range(len(words)):
    if not words[i].isalpha():
        words[i]=""

In [14]:
len(words)

785472

In [15]:
for i in range(len(words_heading)):
    if not words_heading[i].isalpha():
        words_heading[i]=""

In [16]:
len(words_heading)

19435

In [17]:
words_dict=Counter(words)

In [18]:
words_new=Counter(words_heading)

In [19]:
len(words_dict)

24139

In [20]:
len(words_new)

6053

In [21]:
del words_dict[""]

In [22]:
len(words_dict)

24138

In [23]:
del words_new[""]

In [24]:
len(words_new)

6052

In [25]:
words_dict=words_dict.most_common(3000)

In [26]:
words_new=words_new.most_common(1200)

In [27]:
star=""
feature=[]
for i in range(2692):
    star=""
    for j in news['Article'][i]:
        star+=j
    blob=star.split(" ")
    data=[]
    for i in words_dict:
        data.append(blob.count(i[0]))
    feature.append(data)

In [28]:
len(feature)

2692

In [29]:
moon=""
sell=[]
for i in range(2692):
    moon=""
    for j in news['Heading'][i]:
        moon+=j
    bluff=moon.split(" ")
    data=[]
    for i in words_new:
        data.append(bluff.count(i[0]))
    sell.append(data)

In [30]:
len(sell)

2692

In [31]:
x=np.hstack((feature,sell))

In [32]:
x.shape

(2692, 4200)

In [33]:
target=[]
for i in range(2692):
    if news['NewsType'][i]==1:
        target.append(news['NewsType'][i])
    if news['NewsType'][i]==0:
        target.append(news['NewsType'][i])

In [34]:
len(target)

2692

In [35]:
y=np.array(target)

In [36]:
y.shape

(2692,)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=7)

In [38]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [39]:
classifier.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [40]:
def converter(sample,head):
    data=[]
    disc=[]
    for i in words_dict:
        data.append(sample.split(" ").count(i[0]))
    for i in words_new:
        disc.append(head.split(" ").count(i[0]))
    email_input=np.hstack((data,disc))
    return email_input.reshape(1,4200)

In [41]:
head="""Federer played well, he deserves it: Nadal on Wimbledon semi-final defeat Rafael Nadal was disappointed with his performance against Roger Federer in Wimbledon 2019 Mens singles semi-final as he missed out on a chance to claim his third Wimbledon crown. """

sample="""ewarding as it was for Rafael Nadal to become the only player to win the same Grand Slam 12 times by chalking up his dozen at last month's French Open, the Spaniard arrived at Wimbledon this year like a man on a mission.
In the end, however, it became mission impossible as he lost to inspired Roger Federer in Friday's blockbuster semi-final.Not since 2010, two years after his epic final triumph over Federer proved the king of clay had mastered grass, has the Spaniard been the last man standing at Wimbledon.
Since that win over Tomas Berdych it has not been a particularly happy hunting ground for the Mallorcan.
After losing to Novak Djokovic in the 2011 final, Nadal has never contested a title decider on Centre Court, suffering shock losses to the likes of Lukas Rosol, Dustin Brown and Gilles Muller, not to mention Nick Kyrgios.
Last year he was close, losing an epic semi to Djokovic when victory would have left him facing an exhausted Kevin Anderson in the final a virtual open goal """

In [42]:
arr=converter(sample,head)

In [43]:
classifier.predict(arr)

array([0], dtype=int64)

In [50]:
min="""Reliance Jio and Piramal Group may set up a joint venture for consumer lending, fintech business
The capital infusion in Piramal Enterprises is likely to be in two tranches, and will be announced shortly """
max="""Billionaire and maverick investor Ajay Piramal's flagship company 
PiramalNSE -0.92 % Enterprises is on the verge of finalising a massive Rs 9600 cr capital 
infusion deal with Softbank and one more party. ET Now has learnt this from several investment banking 
sources and lawyers working on the transaction. It was not possible to however to ascertain the name of the 
second party that will be infusing capital into the Piramal Group. 
The capital infusion in Piramal Enterprises is likely to"""

In [51]:
arr=converter(max,min)

In [52]:
classifier.predict(arr)

array([1], dtype=int64)

In [53]:
high="""India targets $47 billion from stake sales in state firms over 5 years: Report
Prime Minister Narendra Modi's administration already sold government stakes in a host
of companies to raise a record USD 40.92 billion in his first five-year term."""

low="""The Indian government has plans to raise as much as 3.25 trillion rupees ($47.4 billion) in the next
five years by reducing its stakes in some large state-owned firms to 40%, two senior government officials told Reuters,
in the nation's biggest privatization push in more than two decades.
Last week, finance minister Nirmala Sitharaman in her budget announced that the government will look to reduce direct 
controlling stakes in some state-run firms on a case-by-case basis.
The plan will open up a steady stream of state companies to greater private investment, and 
target the kind of annual divestment revenue that will be crucial to meet fiscal deficit targets.
Prime Minister Narendra Modi's administration already sold government stakes in a host of companies to
raise a record $40.92 billion in his first five-year term, nearly three times the divestment proceeds of 
$14.52 billion achieved by the Congress party government in 2009-2014. Modi was re-elected for a second-term in a landslide 
victory in April-May."""

In [54]:
arr=converter(low,high)

In [55]:
classifier.predict(arr)

array([1], dtype=int64)

In [56]:
get="""I am ready to knock down Mike Snider: Vijender Singh on his comeback bout
Star Indian boxer Vijender Singh will make a return to the ring after a gap of more than a
year against American Mike Snider on July 13."""

take="""After a hiatus of more than one year, star Indian boxer Vijender Singh will be back in action against American Mike Snider in an eight-round super middleweight contest here on Saturday.
WBO Oriental and Asia Pacific super middleweight champion Vijender has a 10-0 (7 knockouts) record so far in his professional career.
I think it's going to be a great show. I'm focused on my boxing career and my craft. I want to fight two more times this year, keep busy and work towards a world title opportunity," he said in the pre-bout press conference.
I am fully geared up for this fight and my strategies against Mike Snider are already in place as discussed with my team, including trainer Lee Beard. I am ready to knock down Snider in the early rounds," he added.
Snider, who holds a record of 13-5-3, said his trainers have seen enough of Vijender and they have their plans for him.
My trainers looked at Vijender and watched several of his fights. 
They told me what he does well and what we can do to exploit his weaknesses. The game plan is going to come from my trainers and what they've seen," he said."""

In [57]:
arr=converter(take,get)

In [58]:
classifier.predict(arr)

array([0], dtype=int64)

In [45]:
y_pred=classifier.predict(x_test)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9925788497217068

In [47]:
y_test

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,

In [48]:
y_pred

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,